table_name: books
common_indexes:
  - books_pkey
scenarios:
  reference:
    - books_price_idx
    - books_available_title_idx
    - books_available_idx
  scenario1:
    - books_price_available_partial
  scenario2:
    - books_price_available_idx
  scenario3:
    - books_available_price_idx
  scenario4:
    - books_title_idx
  scenario5:
    - books_title_idx
    - books_available_price_idx